load_model_fp: './ckpt/lite_medsam.pth'
teacher_model_fp: './ckpt/medsam_vit_b.pth'
save_model_dir: './ckpt/LiteMedSAM.tune'
save_model_name: 'litemedsam_tune_ie'
train_dataset_dir: '../dataset/MedSAMLaptop/split_set/train_ext'

sampler_strategy: 'OneTenth'
image_size: 256
bbox_shift: 10
augment: True

quant_ie: False
quant_md: False
train_ie: True
train_pe: False
train_md: False
warmup_epochs: 3
cosine_epochs: 10
batch_size: 2
