load_model_fp: './ckpt/quantized_dist2/ie/quantized_dist_ie.e16.pth'
teacher_model_fp: 
save_model_dir: './ckpt/quantized_dist2/iemd'
save_model_name: 'quantized_dist_iemd'
train_dataset_dir: '../dataset/MedSAMLaptop/split_set2/train_ext'

sampler_strategy: 'Min'
image_size: 256
bbox_shift: 10
augment: True

quant_ie: True
quant_md: True
train_ie: False
train_pe: False
train_md: True
warmup_epochs: 5
cosine_epochs: 10
batch_size: 4
